// Generated by CoffeeScript 1.6.2
(function() {
  var app, config, express, rjs;

  express = require('express');

  rjs = require('rjs').installPrototypes();

  config = require('./config.js').config;

  app = express();

  app.set('view engine', 'jade');

  app.set('views', __dirname + '/views');

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: config.sessionSecret
  }));

  app.use(express["static"](__dirname + '/public'));

  app.use(express["static"](__dirname + '/bower_components'));

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.get('/teach', function(req, res) {
    return res.render('teach');
  });

  app.get('/learn', function(req, res) {
    return res.render('learn');
  });

  app.listen(process.env.PORT, function() {
    return console.log('Listening on port ' + process.env.PORT);
  });

  exports.app = app;

}).call(this);
